:setlocal shiftwidth=2
:setlocal tabstop=2
:setlocal softtabstop=2
:setlocal expandtab
":setlocal foldenable
":setlocal foldmethod=manual
:setlocal nu
:colorscheme colors
:setlocal noautoindent
:syntax enable
